name: name: Send WhatsApp Daily 🚀

on:
  schedule:
    - cron: '0 6 * * *'   # 8 صباحًا بتوقيت مصر
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
        run: python main.py
